### ISSUE TITLE
Choix du xebian parmi deux photos

### ISSUE THREAD

**Issue by seblm** [xebia-france/xwhois#1]
En tant que xebian je veux pouvoir choisir entre deux photos de xebian correspondant au nom qui m'est demandé et de voir quelle était la bonne réponse afin de pouvoir apprendre par coeur le nom de chaque xebian.

**Comment by alexandrehebert** [comment]
Must have !
Je me lance là-dessus.
En parallèle, je mets en place les premiers tests e2e.
