### ISSUE TITLE
Dockerfile pour Mongodb

### ISSUE THREAD

**Issue by seblm** [xebia-france/xwhois#14]
Pour faciliter le dev.

Le lier à gulp au lancement des tests.

**Comment by alexandrehebert** [comment]
Cela semble compliqué d'utiliser une image docker, dans la mesure ou on travaille sous mac et que je ne peux pas utiliser une simple ligne de commande pour run/stop l'image.

Proposition : utiliser une image vagrant.

**Comment by seblm** [comment]
Avec les infos sur le README ça ne devrait pas être si compliqué que ça.
Il reste à ajouter un peu de doc sur le montage du volume (pour conserver la base entre deux redémarrages du conteneur).
