### ISSUE TITLE
Environnement de dev : page semi-blanche

### ISSUE THREAD

**Issue by geekarist** [xebia-france/xwhois#16]
J'ai installé mon environnement comme indiqué dans le README, j'arrive à accéder à la page d'accueil, mais quand je clique sur Play, j'ai une page "semi-blanche".

J'ai démarré Mongo comme ceci :

```
$ docker run mongo
2015-04-21T18:47:44.919+0000 I JOURNAL  [initandlisten] journal dir=/data/db/journal
[...]
2015-04-21T18:47:45.043+0000 I NETWORK  [initandlisten] waiting for connections on port 27017
```

Et l'appli :

```
$ gulp build && CONFLUENCE_HOSTNAME=intranet.xebia.com CONFLUENCE_USER=cpele CONFLUENCE_PASSWORD="xxxxxxx" CONFLUENCE_RESOURCE_ID=4522409 node server.js
[20:44:39] Requiring external module coffee-script/register
[20:44:41] Build in development mode.
[...]
[20:44:43] Finished 'clean:after-build' after 86 μs
[20:44:43] Finished 'build' after 1.55 s
GET / 200 6.692 ms - 610
GET /app.final.js 200 2.257 ms - 14616
GET /styles.css 200 3.514 ms - 68830
GET /libs/vendors.js 200 41.948 ms - 1456674
GET /assets/images/background.jpg 200 1.159 ms - 336047
GET /assets/fonts/emulogic.ttf 200 0.963 ms - 45480
GET /assets/images/logo.png 200 0.997 ms - 20962
GET /styles.css 304 0.730 ms - -
```

Ce qui me semble correct, mais voici la page blanche :

![screen shot 2015-04-21 at 20 45 57](https://cloud.githubusercontent.com/assets/1910698/7260297/51d117e2-e869-11e4-88b0-952e90e81633.png)

**Comment by seblm** [comment]
Le projet est en chantier :disappointed:
Il s'agit d'une boucle infinie sur le choix des deux noms à trouver.
J'ai résolu le problème référencé par #17.
J'ai également poussé a639f9f qui crée insère juste deux personnes au démarrage du serveur.

**Comment by seblm** [comment]
La dépendance à MongoDB n'est pas encore utilisée sur le projet. Tu peux t'éviter le démarrage du serveur pour l'instant.

**Comment by seblm** [comment]
@geekarist  si j'ai répondu à ta question, tu peux fermer ce ticket.
