### ISSUE TITLE
Déploiement de l'application

### ISSUE THREAD

**Issue by seblm** [xebia-france/xwhois#7]
Utiliser une instance Amazon qui contient un Node, un Mongodb et l'appli packagée.

**Comment by joe-mojo** [comment]
Ça serait pas moins cher Amazon Beanstalk pour le Node + une petite instance pour mongodb ? 

Joachim

**Comment by alexandrehebert** [comment]
On prend toutes les propositions, pourvu quelles soient économique et simple à la mise en place ! Donc pourquoi pas ! Pour information, l'application contient une application SPA (angular), et quelques services exposés en node. On partait sur une solution ou tout serait colocalisé sur la même machine, au regard des volumétries.

**Comment by joe-mojo** [comment]
Demande à un expert du cloud AWS genre Charles Blonde, ça vaut le coup de comparer.

Joachim

**Comment by pvardanega** [comment]
Voici une possibilité : 
- pour mongodb, vous pouvez utiliser gratuitement mongolab ou mongohq. Vous aurez la possibilité de créer autant de base de données que vous les souhaitez. La seule limite est de 500 Mo pour toutes les bases créées. J'utilise mongolab pour l'appli XKE. Je le préfère car l'interface d'admin est bien plus simple et complète,
- pour le back en Node, vous pouvez le déployer sur amazon beanstalk,
- pour le front, il existe un plugin gulp pour déployer les sources sur la branche gh-pages de github.

**Comment by joe-mojo** [comment]
Du coup Beanstalk + mongo(?:lab|hq) serait moins cher ...
Xebia.tv est sous Beanstalk par exemple

Joachim

**Comment by alexandrehebert** [comment]
Okay, dans ce cas on part là-dessus ! Merci pour vos conseils avisés :) !!!

**Comment by seblm** [comment]
Mongo est déployé sur aws, l'appli est déployée sur heroku.
