### ISSUE TITLE
Trombinoscope doit être exécuté tous les jours

### ISSUE THREAD

**Issue by seblm** [xebia-france/xwhois#8]
- parser la page trombinoscope pour obtenir la date de dernière modification
- checker si on doit mettre à jour à partir de la date de dernière modification qu'on a enregistré en base
- si oui synchroniser avec la base, télécharger les images, les stocker dans mongodb
- mettre en place un CRON pour exécuter ce module tous les jours

**Comment by alexandrehebert** [comment]
http://docs.mongodb.org/manual/core/gridfs/ est peut-être la solution de stockage pour les images dans Mongo.
